apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-prio
value: 100000
globalDefault: false
description: "This is pretty high."
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: low-prio
value: -1000
globalDefault: true
description: "This is quite low."
