apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  another-param: another-value
  extra-param: extra-valuehaha
  my-config.txt: |
    # This is a sample config file that I might use to configure an application
    parameter1 = value1
    parameter2 = value2
    parameter3 = value3
