apiVersion: v1
kind: Service
metadata:
  name: sample-webhook-service-svc
  labels:
    app: sample-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: sample-webhook-service