apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sample-webhook-service
  labels:
    app: sample-webhook-service
webhooks:
  - name: devops.kubernetes.com
    admissionReviewVersions: ["v1", "v1beta1"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: sample-webhook-service-svc
        namespace: default
        path: "/"
      caBundle: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lSQUw5MHd6aDlubDNRTmxjMk1vZ3Jvc0F3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pESmxOV0l3TURNdE5EQTBNeTAwTXpFeUxUbGtPVFF0TmpRMFlqTXpOemt4WVRNMgpNQjRYRFRJeE1EY3hPVEUzTVRjeE5sb1hEVEkyTURjeE9ERTRNVGN4Tmxvd0x6RXRNQ3NHQTFVRUF4TWtaREpsCk5XSXdNRE10TkRBME15MDBNekV5TFRsa09UUXROalEwWWpNek56a3hZVE0yTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBekpNcU9ubXNwZ2tZVEdzV0FVaEkzK29zK2JrSXRwSHRBMVRPZmEwNQo3RFVzdW8va0dHc0E2Szh1RkM2VUxyOTI1bEd0S2xzVVNySCtHdTFFSUN2RFpYTjFFekdUOE84SE9KWldGM0JTCjd2eEoxeVZZZjc2bVVnZVpQbXpLa2xMdVo5RmRUV3VYNjhISXhOZkQwdjJQVFFBWTdqV0krQldpUERIMndjTUMKUE1sUm5LcldnWm5lK0ExRWwvK3g2eFBzRUhlYUtmOTFHUXdHYlFWR3poRG1nNHdWZVBHRSs4S1hrb1NIZUR6aQpYMC9PZzlxLzJSZEFneU1MWkVHL1hWaStYWHJvajZFVUdNVzZxYmxBUTBZUXNOTFI3WE1qVTcxaGxNdzh2L3N6CkprY0ExZzBiZUdxci8xaDBNQkUwZVBFMzR6MEcrUUpLdE5DSzBCb2JhOTJnK1FJREFRQUJvMEl3UURBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXZJUWYzK1dWcnJIMApMdlpMRWp0dGdJYnNxbEF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdTdnBwN3hLeDhYZmF4Ujc3YytmU3BJCnRUR2RadjdpMmtUSmpHVmMyeUNFRlRBN2sxYWZ2NmVPOVhNQlBFQldScERKc2RtQ1VuUHhEbUFET3ByNFp2OHoKL09zZUY2OGhzWEVhVzZ1NFFDbTByN1VrTSsrN1dRbDM1Y1FBUVJZNlBadU83RWRVRHZGaWFrV2lKK0tTbWwrWAo3YXphckdWUjRUdC9RUGloN2VmZE02UGNDMUdWUFNFNnEzeHorRTJmdzJlQ3JKWEtFUVM2Z3ljYnVtMHZsejM2Ck1TK2RMVXQxR1crOS9ETDRpUDNuL3pRTTZqUEhsVEFPZUs5SUZUTHVESTBHb1R6R2VVMm9WeHl2d2hjdlRuVjcKaHR4YTNEYXdkZ0Q4RGpXZFlCaTRpaTFSRWtSS2l5V2dLb2oxa3pFS2RKQmVPWHpWNStRZ1dtb1FKNnNDMUZJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=='