apiVersion: v1
kind: Namespace
metadata:
  name: team-capybara
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitcage-container
  namespace: team-capybara
spec:
  limits:
  - default:
      cpu: 0.5
      memory: 512Mi
    defaultRequest:
      cpu: 0.25
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitcage-pods
  namespace: team-capybara
spec:
  limits:
  - max:
      cpu: 0.5
      memory: 512Mi
    min:
      cpu: 0.25
      memory: 256Mi
    maxLimitRequestRatio:
      cpu: 1.2
    type: Pod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitcage-storage
  namespace: team-capybara
spec:
  limits:
  - max:
      storage: 10Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
