apiVersion: v1
kind: Namespace
metadata:
  name: team-capybara
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-pods
  namespace: team-capybara
spec:
  hard:
    count/pods: 1
  scopes:
  - BestEffort
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-resources
  namespace: team-capybara
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 1Gi
  scopes:
  - NotBestEffort
---
apiVersion: batch/v1
kind: Job
metadata:
  name: capybara
  namespace: team-capybara
spec:
  parallelism: 20
  completions: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: fattyworkload
        image: busybox
        command: ["/bin/sh", "-c", "sleep 5"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: politer-capybara
  namespace: team-capybara
spec:
  parallelism: 20
  completions: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: fattyworkload
        image: devopswithkubernetes/stress
        args: ["--vm-keep", "--vm", "1", "--vm-bytes", "1M", "--timeout", "5"]
        resources:
          limits:
            cpu: 25m
            memory: 25M
