apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-logging
  template:
    metadata:
      labels:
        app: kibana-logging
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:6.4.2
        name: kibana-logging
        command:
        - /bin/bash
        - -c
        - |
          bin/kibana-plugin remove x-pack ;
          /usr/local/bin/kibana-docker
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: "http://es-logging-svc:9200"
        volumeMounts:
        - name: config-file
          mountPath: /usr/share/kibana/config
      volumes:
      - name: config-file
        configMap:
          name: kibana-config-file
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging-svc
  namespace: logging
spec:
  ports:
  - port: 5601
  selector:
    app: kibana-logging
