apiVersion: batch/v1
kind: Job
metadata:
  name: gen-n-apply-cert
  namespace: custom-metrics
spec:
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: apply-cert-in-current-ns
        image: devopswithkubernetes/apply-cert-secret
        env:
        - name: SERVICENAME
          value: custom-metrics-apiserver
        - name: NAMESPACE
          value: "custom-metrics"
        - name: SECRETNAME
          value: "cm-adapter-serving-certs"
      restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer
  namespace: custom-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-writer
subjects:
- kind: ServiceAccount
  name: default
  namespace: custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: custom-metrics
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
