kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fastzrs
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Premium_ZRS
  location: centralus

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slowzrs
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_ZRS
  location: centralus
