apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: etcd-server-svc
  labels:
    k8s-app: etcd-server
    prom-target: etcd
    component: prometheus
    task: scrape
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '2379'
spec:
  clusterIP: None
  ports:
  - name: etcd-server
    port: 2379
  selector:
    k8s-app: etcd-server
