apiVersion: config.istio.io/v1alpha2
kind: logentry
metadata:
  name: accesslog
  namespace: istio-system
spec:
  severity: '"info"'
  timestamp: request.time
  variables:
    source: source.labels["app"] | source.workload.name | "unknown"
    sourceIp: source.ip | ip("0.0.0.0")
    destination: destination.labels["app"] | destination.workload.name | "unknown"
    destinationIp: destination.ip | ip("0.0.0.0")
    user: source.user | ""
    method: request.method | ""
    url: request.path | ""
    protocol: request.scheme | ""
    responseCode: response.code | 0
    responseSize: response.size | 0
    requestSize: request.size | 0
    latency: response.duration | "0ms"
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: fluentd
  namespace: istio-system
spec:
  compiledAdapter: fluentd
  params:
    address: fluentd-aggegater-svc.logging:24224
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: accesslogtofluentd
  namespace: istio-system
spec:
  match: "true"
  actions:
  - handler: fluentd
    instances:
    - accesslog.logentry
