apiVersion: v1
kind: Service
metadata:
  name: fluentd-aggegater-svc
  namespace: logging
  labels:
    app: fluentd-aggegater
spec:
  selector:
    app: fluentd-aggegater
  ports:
  - name: fluentd-tcp
    port: 24224
    protocol: TCP
    targetPort: 24224
  - name: fluentd-udp
    port: 24224
    protocol: UDP
    targetPort: 24224