apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: books.devops.kubernetes.com
spec:
  group: devops.kubernetes.com
  names:
    kind: Book
    listKind: BookList
    plural: books
    singular: book
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
