apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-2nd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-2nd-app
  template:
    metadata:
      labels:
        app: my-2nd-app
    spec:
      readinessGates:
      - conditionType: "MY-GATE-1"
      containers:
      - name: main
        image: devopswithkubernetes/okeydokey:v0.0.4
---
kind: Service
apiVersion: v1
metadata:
  name: my-2nd-app-svc
  labels:
    app: my-2nd-app
spec:
  selector:
    app: my-2nd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
